# Generated by Django 4.1.7 on 2023-05-07 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("carrinhos", "0002_remove_carrinho_user"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="carrinho",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carrinho_user",
                to="carrinhos.carrinho",
            ),
        ),
    ]
