# Generated by Django 4.1.7 on 2023-05-07 12:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_carrinho"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="carrinho",
        ),
    ]
