# Generated by Django 4.1.7 on 2023-05-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("categorias", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=30)),
                ("descricao", models.TextField(max_length=255)),
                (
                    "img",
                    models.URLField(
                        default="https://as1.ftcdn.net/v2/jpg/05/04/28/96/1000_F_504289605_zehJiK0tCuZLP2MdfFBpcJdOVxKLnXg1.jpg",
                        max_length=255,
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=8)),
                ("quantidade_estoque", models.IntegerField()),
                ("disponibilidade", models.BooleanField(default=True)),
                ("vendidos", models.IntegerField(default=0)),
                (
                    "categorias",
                    models.ManyToManyField(
                        related_name="produtos", to="categorias.categoria"
                    ),
                ),
            ],
        ),
    ]
