# Generated by Django 4.1.7 on 2023-05-05 08:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("produtos", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="produto",
            options={"ordering": ["id"]},
        ),
    ]
