# Generated by Django 4.1.7 on 2023-05-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produtos", "0003_alter_produto_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="descricao",
            field=models.TextField(),
        ),
    ]
