# Generated by Django 4.1.7 on 2023-05-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categorias", "0001_initial"),
        ("produtos", "0004_alter_produto_descricao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="categorias",
            field=models.ManyToManyField(
                related_name="produtos_cat", to="categorias.categoria"
            ),
        ),
    ]
