# Generated by Django 4.1.7 on 2023-05-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pedidos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="valor_total",
            field=models.IntegerField(default=0),
        ),
    ]
