# Generated by Django 4.1.7 on 2023-05-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        choices=[
                            ("Informática", "Informatica"),
                            ("Eletrodomésticos", "Eletrodomesticos"),
                            ("Casa", "Casa"),
                            ("Livros", "Livros"),
                            ("Eletrônicos", "Eletronicos"),
                            ("Games", "Games"),
                            ("Brinquedos", "Brinquedos"),
                            ("Crianças", "Criancas"),
                            ("Not Informed", "Default"),
                        ],
                        default="Not Informed",
                        max_length=127,
                    ),
                ),
            ],
        ),
    ]
