# Generated by Django 4.1.7 on 2023-05-05 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("produtos", "0003_alter_produto_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carrinho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qtd_total", models.IntegerField(blank=True, null=True)),
                ("preco_total", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="CarrinhoProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.IntegerField(blank=True, default=1)),
                (
                    "carrinho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carrinho_produto_carrinhos",
                        to="carrinhos.carrinho",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carrinho_produto_produto",
                        to="produtos.produto",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="carrinho",
            name="produtos",
            field=models.ManyToManyField(
                related_name="produto_carrinho",
                through="carrinhos.CarrinhoProduto",
                to="produtos.produto",
            ),
        ),
        migrations.AddField(
            model_name="carrinho",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carrinho",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
