# Generated by Django 4.1.7 on 2023-05-07 11:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("carrinhos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carrinho",
            name="user",
        ),
    ]
